### ISSUE TITLE
cannot redefine property $http using axios

### ISSUE THREAD

**Issue by kanwal-github** [diadal/vue-social-auth#12]
TypeError: Cannot redefine property: $http     at Function.defineProperties (<anonymous>)     at o (vue-axios.min.js?a7fe:1)     at Function.Vue.use (vue.runtime.esm.js?2b0e:5103)
when it comes to this.$auth it gives above error.
  this.$auth.authenticate(provider).then(response => {
          self.SocialLogin(provider, response)
        }).catch(err => {
          console.log({ err: err })
        })

![image](https://user-images.githubusercontent.com/57522965/68476102-aa3abb80-024b-11ea-91c5-de942a6b1a34.png)

**Comment by diadal** [comment]
Check your code if you have already use $http twice

**Comment by kanwal-github** [comment]
can u please share what this.$auth does ?
`<template>
  <validation-observer ref="obs">
    <v-container
      id="login"
      class="fill-height"
      tag="section"
    >
      <v-row justify="center">
        <v-slide-y-transition appear>
          <base-material-card
            color="success"
            light
            max-width="100%"
            width="400"
            class="px-5 py-3"
          >
            <template v-slot:heading>
              <div class="text-center">
                <h1 class="display-2 font-weight-bold mb-2">
                  Login
                </h1>

                <v-btn
                  class="ma-1"
                  icon

                  @click="AuthProvider('facebook')"
                >
                  <v-icon
                    v-text="'mdi-facebook-box'"
                  />
                </v-btn>
                <v-btn
                  class="ma-1"
                  icon

                  @click="AuthProvider('twitter')"
                >
                  <v-icon
                    v-text="'mdi-twitter'"
                  />
                </v-btn>
                <v-btn
                  class="ma-1"
                  icon

                  @click="AuthProvider('google')"
                >
                  <v-icon
                    v-text="'mdi-google'"
                  />
                </v-btn>
              </div>
            </template>

            <v-card-text class="text-center">
              <div class="text-center grey--text body-1 font-weight-light">
                Or Be Classical
              </div>
              <validation-provider
                name="email"
                rules="required|email"
              >
                <v-text-field
                  v-model="user_form.email"
                  slot-scope="{errors,valid }"
                  color="secondary"
                  label="Email..."
                  :error-messages="errors"
                  :success="valid"
                  prepend-icon="mdi-email"
                />
              </validation-provider>
              <validation-provider
                ref="incorrect"
                name="password"
                rules="required"
              >
                <v-text-field
                  v-model="user_form.password"
                  slot-scope="{errors,valid }"
                  class="mb-8"
                  color="secondary"
                  label="Password..."
                  :error-messages="errors"
                  :success="valid"
                  prepend-icon="mdi-lock-outline"
                  type="password"
                />
              </validation-provider>
              <div class="error">
                {{ errors.first('incorrect') }}
              </div>
              <pages-btn
                large
                color=""
                depressed
                class="v-btn--text success--text"
                @click="login"
              >
                Let's Go
              </pages-btn>
            </v-card-text>
          </base-material-card>
        </v-slide-y-transition>
      </v-row>
    </v-container>
  </validation-observer>
</template>

<script>
  import Vue from 'vue'
  // import VueAxios from 'vue-axios'
  import { mapActions } from 'vuex'
  import VueSocialauth from 'vue-social-auth'
  // import axios from 'axios';
  import {
    ValidationObserver,
    ValidationProvider,
  //  withValidation
  } from 'vee-validate'

  // Vue.use(VueAxios,axios)

  Vue.use(VueSocialauth, {

    providers: {
      google: {
        clientId: '********',
        redirectUri: '/auth/google/callback', // Your client app URL
      },
    },
  })

  export default {
    name: 'PagesLogin',
    inject: ['$validator'],
    components: {
      ValidationProvider,
      ValidationObserver,
      PagesBtn: () => import('./components/Btn'),
    },
    data: () => ({
      user_form: {
        email: '',
        password: '',
      },
    }),
    mounted () {
      if (this.$store.state.user.isLoggedIn && this.$store.state.user.role === 'ADMIN') {
        this.$router.push('admin/users')
      } else if (this.$store.state.user.isLoggedIn && this.$store.state.user.role === 'USER') {
        this.$router.push('/dashboard')
      }
    },

    methods: {
      ...mapActions(['doLogin']),
      async login () {
        const result = await this.$refs.obs.validate()
        if (result) {
          this.doLogin(this.user_form).then(
            () => {
              if (this.$store.state.user.role === 'ADMIN') {
                this.$router.push('admin/users')
              } else {
                this.$router.push('/dashboard')
              }
            },
            error => {
              this.$validator.errors.add({
                field: 'incorrect',
                msg: error.data.response,
              })
            }
          )
        }
      },
      AuthProvider (provider) {
        var self = this
        alert(provider)
        this.$auth.authenticate(provider).then(response => {
          alert(response)
          self.SocialLogin(provider, response)
        }).catch(err => {
          console.log({ err: err })
        })
      },

      SocialLogin (provider, response) {
        this.$http.post('/sociallogin/' + provider, response).then(response => {
          console.log(response.data)
        }).catch(err => {
          console.log({ err: err })
        })
      },

    },

  }

</script>
`

**Comment by diadal** [comment]
this.$auth Connect to VueSocialauth
