### ISSUE TITLE
GOOGLE ERROR 400 MISSING SCOPE

### ISSUE THREAD

**Issue by VAUNT** [diadal/vue-social-auth#13]
Hello, 

when i try to use the google provider i have this issue in the google popup, who i can solve it ? 

```
400. That’s an error.

Error: invalid_request

Missing required parameter: scope
```

thx

**Comment by VAUNT** [comment]
I have found why this problem occur...

You need in the plugin to pass the "scope" before the "redirect_uri" and pass the "scope "params with a "+" between each

**Comment by diadal** [comment]
Can you submit the pull
