### ISSUE TITLE
Docs and Usage 

### ISSUE THREAD

**Issue by thekubilay** [diadal/vue-social-auth#16]
I have a couple question because the docs is not very clear. First, when you say USAGE, you mean creating a file like `auth.js` or is it a template? Because right below the usage there is a couple of Button??? and those are not inside Vew (I think you mean view) there. 

Could you please create a example folder and put the files how it should be... OR could please renew the docs. It would be really helpful.

**Comment by diadal** [comment]
The button inside your View file then before button in your app.js file
