### ISSUE TITLE
Clear list of supported providers

### ISSUE THREAD

**Issue by Truemedia** [diadal/vue-social-auth#18]
Hi,
Great project by the way I have this working with the github, and facebook providers nicely.

Just a suggestion looking at the docs it makes it seems as if you support all the socialite third party providers when in fact only a very small fraction of them are supported out of the box by this project.

The only way I could find out exactly which ones were supported was digging in the code for 10-15 mins to eventually find them in the 'src/options.js'. Would it not be nicer to just have a section in the README which specifically states which providers you can use out of the box with this, thanks.

**Comment by diadal** [comment]
can you submit the PR please very busy with other things at the moment thanks
