### ISSUE TITLE
CALLBACK is problem

### ISSUE THREAD

**Issue by JulioCCosta** [diadal/vue-social-auth#2]
I have two projects (api = laravel and client = vuejs) my real problem is that in the callback it redirects me to my api, how do I return to my client?

**Comment by diadal** [comment]
create from your Api route 

```

Route::post('api/sociallogin/{provider}', 'YourAuthController@SocialSignup');
Route::post('api/auth/{provider}', 'YourOutController@index')->where('vue', '.*');
Route::post(api/'auth/{provider}/callback', 'YourOutController@index')->where('vue', '.*');

```

than

```

YourAuthController


<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Socialite;

class AuthController extends Controller
{
    

    public function __construct()
    {

    }

    
    public function SocialSignup($provider)
    {
        // Socialite will pick response data automatic 
        $user = Socialite::driver($provider)->stateless()->user();

        return response()->json($user);
    }

}


```

**Comment by JulioCCosta** [comment]
@diadal I'm doing this, the problem is that in my client (vuejs) when I try to callback the package it only returns the code and not the token

![socialcontroller](https://user-images.githubusercontent.com/17937619/56383792-235fbc00-61f1-11e9-9389-c6529411b813.PNG)
![image](https://user-images.githubusercontent.com/17937619/56383821-32466e80-61f1-11e9-97c6-00bb4501148c.png)

**Comment by diadal** [comment]
this `return response()->json($user);` and `dd($user)` are different

**Comment by diadal** [comment]
make sure your callback route point back to your index page `Route::post(api/'auth/{provider}/callback', 'YourOutController@index')->where('vue', '.*')`

then 


Vue Router
```
        {
          path: 'api/auth/:provide/callback',
          component: {
            template: '<div class="auth-component"></div>'
          }
        },

```
