### ISSUE TITLE
Pop-up always redirect to login page in iPhone

### ISSUE THREAD

**Issue by gabmaxs** [diadal/vue-social-auth#20]
I have a PWA application with Vue and Laravel and social login with facebook or google providers. When clicked in the button to login, the popup open a application's login page, not provider page, and when clicked again only application's login page are load in loop. 

This only happens in iPhone dispositives, i had tested in windows browser, Mac browser and Android browser and it works correcty.

This is a gif from problem record when a try to debug in iPhone simulator: 

![gif-1o1](https://user-images.githubusercontent.com/24658948/74865096-5ef67580-532f-11ea-845c-7e7f96611954.gif)

**Comment by diadal** [comment]
working can you share your `Vue` code also did you create Vue route

**Comment by gabmaxs** [comment]
in main.js: 
![image](https://user-images.githubusercontent.com/24658948/74867883-39b83600-5334-11ea-953b-d2cbb180c7ce.png)

in router.js: 
I use the IonicVueRouter instead of VueRouter
![image](https://user-images.githubusercontent.com/24658948/74868231-acc1ac80-5334-11ea-97c1-aa7de6857d0a.png)

and i added this code to block some pages unless user has logged in
![image](https://user-images.githubusercontent.com/24658948/74868150-94519200-5334-11ea-8b4c-bbe032c501aa.png)


Needs anything else?

**Comment by diadal** [comment]
disable Auth check for now and try I mean comment out router.beforeEach then try see if you get social login page

**Comment by gabmaxs** [comment]
did some tests and it works, have any idea why?? haha
and any suggestions to do Auth check with another way?

**Comment by diadal** [comment]
you checking Auth before login process completed change your method.

mine 

```

router.beforeResolve((to, from, next) => {

  if (to.matched.some(record => record.meta.middlewareAuth)) {                
        if (!AuthData.check()) {
            next('/login');

            return;
        }
    }
 }
})

```

**Comment by diadal** [comment]
also try get the correct route path login process need to pass Auth check

**Comment by gabmaxs** [comment]
thats worked, thank you so much for helping
