### ISSUE TITLE
Pop up not closing in production

### ISSUE THREAD

**Issue by Ikpeba4ll** [diadal/vue-social-auth#21]
Pop up windows works in dev mode but doesn't work in production mode> How do i solve this issue??

**Comment by diadal** [comment]
it should work check your webpack.mix

**Comment by ajayinnovia** [comment]
I am facing similar issue. Pop up window sometime works and most of the time does not. 
Anyone who have fixed this issue?

**Comment by diadal** [comment]
try debug your `Vue` component it maybe issue with `eslint` or `babel`

**Comment by ebrahimMaher** [comment]
same issue here !!

**Comment by diadal** [comment]
did you create this route 

```
 {
          path: '/auth/:provider/callback',
          component: {
            template: '<div class="auth-component"></div>'
          }
        },

```
