### ISSUE TITLE
Invalid app identifier

### ISSUE THREAD

**Issue by h-guerrero** [diadal/vue-social-auth#22]
Hi, I am trying to implement your package but when I click the facebook button a facebook modal opens with the Invalid app identifier message. I already setup the following:

Vue.use(VueSocialAuth, {
        facebook: {
            clientId: 'mi-app-identifier',
            redirectUri: '/oauth/facebook/callback',
        }
    });

Have you an idea why this is happening? The fb app is already in use but now I am trying to add the login button in my vue app also. Thanks!

**Comment by diadal** [comment]
check your backend

**Comment by h-guerrero** [comment]
could you be more specific? I have setted the values on .env in the backend

**Comment by h-guerrero** [comment]
by the way, when the facebook's popup opens I can see in the url bar that no clientId was setted, like the following:

https://www.facebook.com/v2.5/dialog/oauth?response_type=code&client_id=&redirect_uri=http%3A%2F%2F127.0.0.1%3A8080%2F&display=popup&scope=email

I followed the instructions.
