### ISSUE TITLE
google error 400 Missing required parameter: client_id

### ISSUE THREAD

**Issue by kiomarsdqeyr** [diadal/vue-social-auth#23]
hi
when i try to use the google provider i have this issue in the google popup, who i can solve it ?
400. That’s an error.

Error: invalid_request

Missing required parameter: client_id

**Comment by diadal** [comment]
Make sure you set the right client_id try console.log your client_id and see if the value is not empty

**Comment by amosappiahnkum** [comment]
This answer may be too late but incase someone has the same issue.

The client id key in the providers object should be camelCase (`clientId` instead of `client_id`).

This worked for me.
