### ISSUE TITLE
Driver [vkontakte] not supported. Pop up not closing.

### ISSUE THREAD

**Issue by KitaXvost** [diadal/vue-social-auth#24]
I connect the first button vue-social-auth (for authorization in VK)

If I prescribe it like this,
```
providers: {
  vkontakte: {
    clientId: '4393061',
    redirectUri: '22zz.ru/home'
  },
```
what happens is this:

The link (client_id, redirect_uri) is formed correctly.
The popup window opens without errors.
after entering data in the authorization form, to the link in the address bar,
added `?code=1234567890` (only in popup window)
authorization worked, but at the same time
the flashing window didn't close
closing the window, I get in the console:
```
{err: Error: Auth popup window closed
    at https://22zz.ru/js/app.js:15418:16}
```
however there are no errors in the logs
the link doesn't change in the main window

and if I change
`redirectUri: 'https://22zz.ru/home'`
I get this in the console:
`POST https://site.ru/sociallogin/vkontakte 500 (Internal Server Error)`
and in the logs I get this:
`Driver [vkontakte] not supported. at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:119)`

I think there is an error in the route. Tell me if I wrote it correctly? :

In the app settings, on the VK server:
 `https://22zz.ru/home`

.env
` VKONTAKTE_REDIRECT_URI=22zz.ru/home  // with https - equally`

vue component
`redirectUri: '22zz.ru/home'  // with https - error 500`

app.js
```
path: '/auth/:provider/callback',
component: {
template: '<div class="auth-component"></div>'
      }
```

**Comment by diadal** [comment]
This issue is your backend check your Laravel log

**Comment by KitaXvost** [comment]
> ```
> providers: {
>    vkontakte: {
>      clientId: '4393061',
>      redirectUri: '22zz.ru/home'
>    },
> ```
> however there are no errors in the logs
> 

>  and if I change
> `redirectUri: 'https://22zz.ru/home'`
> 
>  I get this in the console:
>  `POST https://site.ru/sociallogin/vkontakte 500 (Internal Server Error)`
> 
>  and in the logs I get this:
>  `Driver [vkontakte] not supported. at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php:119)
> `

**Comment by diadal** [comment]
move to this  https://github.com/diadal/universal-social-auth  and add it with custom method
