### ISSUE TITLE
[BUG] Package in production environment do not turn off popup and return rusult

### ISSUE THREAD

**Issue by lekhang2512** [diadal/vue-social-auth#25]

**Comment by starofsky** [comment]
I have the same issue, will show welcome page, not closing pop-up
![image](https://user-images.githubusercontent.com/5322431/83942478-d805d400-a81d-11ea-9492-53d039c574f1.png)

**Comment by starofsky** [comment]
More info: I used firefox with add-on https://addons.mozilla.org/en-US/firefox/addon/facebook-container/
When I disabled this add-on will close popup. But in production, sometime it still not close pop-up.
Can you check again?

**Comment by lekhang2512** [comment]
> More info: I used firefox with add-on https://addons.mozilla.org/en-US/firefox/addon/facebook-container/
> When I disabled this add-on will close popup. But in production, sometime it still not close pop-up.
> Can you check again?
> 
> Thank you so much.

I used the original code and it works with me

[Login.vue.zip](https://github.com/diadal/vue-social-auth/files/4790923/Login.vue.zip)

**Comment by starofsky** [comment]
> 
> 
> > More info: I used firefox with add-on https://addons.mozilla.org/en-US/firefox/addon/facebook-container/
> > When I disabled this add-on will close popup. But in production, sometime it still not close pop-up.
> > Can you check again?
> > Thank you so much.
> 
> I used the original code and it works with me
> 
> [Login.vue.zip](https://github.com/diadal/vue-social-auth/files/4790923/Login.vue.zip)

Do you use that add-on with Firefox?

**Comment by lekhang2512** [comment]
> > > More info: I used firefox with add-on https://addons.mozilla.org/en-US/firefox/addon/facebook-container/
> > > When I disabled this add-on will close popup. But in production, sometime it still not close pop-up.
> > > Can you check again?
> > > Thank you so much.
> > 
> > 
> > I used the original code and it works with me
> > [Login.vue.zip](https://github.com/diadal/vue-social-auth/files/4790923/Login.vue.zip)
> 
> Do you use that add-on with Firefox?

Well I tried the original code as I sent it to you and it works

**Comment by diadal** [comment]
Can you submit PR very busy with other project

**Comment by diadal** [comment]
move to this  https://github.com/diadal/universal-social-auth
