### ISSUE TITLE
The response code not working with laravel sociallite

### ISSUE THREAD

**Issue by Rik0253** [diadal/vue-social-auth#27]
After successfull login I am getting a response code which i am sending to laravel function but it gives error

Client error: `POST https://graph.facebook.com/v3.3/oauth/access_token` resulted in a `400 Bad Request` response:↵{"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you  (truncated...)↵"

**Comment by diadal** [comment]
Make sure the callback url at your Fb app matches the one at your backend

**Comment by Rik0253** [comment]
When i am putting the same url it shows Home page of laravel app but not get the user data?

**Comment by diadal** [comment]
You need to check your Laravel socialite

**Comment by Rik0253** [comment]
If i am using socialite normally its working but I cannot sent response back to vue as both r in different server.
Can you please suggest how to get the user from you app code?

**Comment by diadal** [comment]
Use socialite stateless make sure all the laravel route and Vue route created accordingly

**Comment by Rik0253** [comment]
Yes all are created but it doesnot work

**Comment by diadal** [comment]
move to this  https://github.com/diadal/universal-social-auth
