### ISSUE TITLE
Twitter provider

### ISSUE THREAD

**Issue by ibadboyjackson** [diadal/vue-social-auth#31]
Hello, 
I test different providers but twitter does not work, when I click a popup opens with a blank page,
then a request is made in POST on in my case http://localhost/auth/twitter.
 I do not know why . The Google and Facebook drivers are working correctly.
Thank you.
![Screenshot from 2021-01sdsqdq-17 21-58-17](https://user-images.githubusercontent.com/74019943/104857313-722f0e00-590f-11eb-9823-47e5fb2d7cc5.png)

**Comment by diadal** [comment]
use this  https://github.com/diadal/universal-social-auth

**Comment by hermanschutte** [comment]
The new package does the same for Twitter though. Also POSTs to `auth/twitter`.

**Comment by diadal** [comment]
you need to use Twitter event in Socialite evert important `https://socialiteproviders.com/Twitter/#installation-basic-usage`

`
protected $listen = [
    \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        // ... other providers
        'SocialiteProviders\\Twitter\\TwitterExtendSocialite@handle',
    ],
];
`

**Comment by hermanschutte** [comment]
The POST to `auth/twitter` still happens and results in a 404 because the route is not defined.

The listener has been added:

```
protected $listen = [
    \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        'SocialiteProviders\\Twitter\\TwitterExtendSocialite@handle',
    ],
];
```
