### ISSUE TITLE
Steam (OpenID) support

### ISSUE THREAD

**Issue by Snakzi** [diadal/vue-social-auth#32]
I have been trying to get this to work, but whenever I want to use steam as my socialite provider, it says "Error: Invalid OAuth type"

Why?

**Comment by Snakzi** [comment]
This is the provider package btw: https://packagist.org/packages/socialiteproviders/steam

**Comment by Snakzi** [comment]
I've just seen that steam uses OpenID instead of OAuth. Is there any option to get steam available on this plugin? Since there are no good solution for steamlogin + vue yet.

**Comment by diadal** [comment]
i can work on this later my hands are full with project which i need to complete in due time but you can work on feel free to submit the pr i can work on this next week

**Comment by diadal** [comment]
The new version will be available before weekend

**Comment by diadal** [comment]
https://github.com/diadal/universal-social-auth

**Comment by diadal** [comment]
use this  https://github.com/diadal/universal-social-auth
