### ISSUE TITLE
Apple Login

### ISSUE THREAD

**Issue by habib3962** [diadal/vue-social-auth#35]
Does it work for Apple login?
Because its not working for me on click button giving me this error in console.
err: Error: Invalid OAuth type

anybody knows?

**Comment by diadal** [comment]
try this `https://github.com/diadal/universal-social-auth`

**Comment by habib3962** [comment]
i am using vue2, universal-social-auth causing issues for me to implement.

**Comment by diadal** [comment]
see this https://github.com/diadal/universal-social-auth-test-vu2
