### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined at errorHandler 

### ISSUE THREAD

**Issue by ruhulrahman** [diadal/vue-social-auth#36]
After popup open when select auth person then close the popup and show this error message:

> err: TypeError: Cannot read property 'status' of undefined at errorHandler (http://localhost:8000/js/chunks/135.6a1bac210ab0004b55e4.js:79:22) at http://localhost:8000/js/chunks/135.6a1bac210ab0004b55e4.js:128:24
message: "Cannot read property 'status' of undefined"
stack: "TypeError: Cannot read property 'status' of undefined\n    at errorHandler (http://localhost:8000/js/chunks/135.6a1bac210ab0004b55e4.js:79:22)\n    at http://localhost:8000/js/chunks/135.6a1bac210ab0004b55e4.js:128:24"
__proto__: Error

**Comment by diadal** [comment]
can you share your code `status` error should be from your code
