### ISSUE TITLE
I am facing this issue  :  Uncaught TypeError: Class constructor VueSocialauth cannot be invoked without 'new'

### ISSUE THREAD

**Issue by AbaidKhan** [diadal/vue-social-auth#39]
When I write this in app.js
Vue.use(VueSocialauth, {
    providers: {
        google: {
            clientId: '',
            client_secret: '',
            redirectUri: 'https://.../auth/google/callback'
        }
    }
});

**Comment by diadal** [comment]
follow the instruction it should work

**Comment by AbaidKhan** [comment]
I have have follow the instructions but It gives me this error. app.js Uncaught TypeError: Class constructor VueSocialauth cannot be invoked without 'new'

**Comment by AbaidKhan** [comment]
> follow the instruction it should work

I have follow the instructions but It gives me this error. app.js Uncaught TypeError: Class constructor VueSocialauth cannot be invoked without 'new'

**Comment by diadal** [comment]
Share your full code

**Comment by diadal** [comment]
you can try with this version https://github.com/diadal/universal-social-auth more stable example here  https://github.com/diadal/universal-social-auth-test-vu2
