### ISSUE TITLE
Request handler instance not found

### ISSUE THREAD

**Issue by rabichawila** [diadal/vue-social-auth#5]
Trying to implement this on nuxtjs, but i keep on getting this error:

**Request handler instance not found**

I am pretty sure that i have `axios` because it comes with nuxt js by default, and i'm using it in my app.

vue-social-auth.js
```
import Vue from 'vue'
import VueSocialauth from 'vue-social-auth'

Vue.use(VueSocialauth, {

  providers: {
      
    google: {
      clientId: 'xxxxxxxx-xxxxxxxxxxx.apps.googleusercontent.com',
      redirectUri: '/auth/google/callback' // Your client app URL
    }

  }
})
```

nuxt.config.js
```
plugins: [ 
    {src: '~/plugins/vue-social-auth', ssr:false},  
 ],
```

component.vue
```
AuthProvider(provider) {
        console.log(this.$auth);
}
```

**Comment by diadal** [comment]
Use the right google ‘clientId’ not app id

**Comment by arhakim** [comment]
Hi,
I have the same issue. 

I follow the auth config from [Socialite](https://socialiteproviders.netlify.com/providers/facebook.html)
`Vue.use(VueSocialauth, {
  providers: {
    facebook: {
	client_id: 'XXX',
	client_secret: 'XXX',
        redirect: '/auth/facebook/callback'
    }
  }
});`

When the button clicked, I got error **Request handler instance not found**

**Comment by soliduskodas** [comment]
https://www.npmjs.com/package/vue-axios - this solved my issue. 

import VueAxios from 'vue-axios'
Vue.use(VueAxios)

**Comment by yoshimitsu7** [comment]
> https://www.npmjs.com/package/vue-axios - this solved my issue.
> 
> import VueAxios from 'vue-axios'
> Vue.use(VueAxios)

Thank you very mutch , i want just to add another thing , it will work fine if you add this:
import axios from 'axios'
import VueAxios from 'vue-axios'
 
Vue.use(VueAxios, axios)
you need to use axios and VueAxios in the some time.

Thanks
