### ISSUE TITLE
Dont know what to do next.

### ISSUE THREAD

**Issue by yabuking84** [diadal/vue-social-auth#6]
Im new to social authentication so please bear with me.

Here is in my main.js
`
providers: {
	    google: {
  			clientId: 'xxxxxxxx-xxxxxxxx.apps.googleusercontent.com',
	    	redirectUri: 'https://myredirect.uri.com/auth/google/callback',
	    }
}`

on my component I have this :
`
authenticate (provider) {
			console.log(this.$auth);
			var ths = this;
			this.$auth.authenticate(provider).then(function (rspns) {
				alert('Social Authentication: ',rspns);
            	ths.SocialLogin(provider,rspns)				
			}).catch((e) => {
				console.log('Error: ' + e);
			})
		},
`

so when I clicked this button `<v-btn @click="authenticate('google')">auth Google</v-btn>` it will open a pop up and show the google accounts to which to sign in with. then after choosing the account it just go to the redirectUri. The pop up doesnt close, it just goes to the redirectUri. Im not sure what to do next. Im not sure also what to do on the redirectUri page. I just want to retrieve that the Google login was a success then get the profile details. 

Thank you.

**Comment by diadal** [comment]
Did you create the Vue route you need to create the Vue route

**Comment by diadal** [comment]
‘’’

        {
          path: '/auth/:provider/callback',
          component: {
            template: '<div class="auth-component"></div>'
          }
        },

‘’’

**Comment by samplecoder122** [comment]
This issue is fixed?
I got the same error for the Facebook and Twitter.
It works well on the localhost but after deploy on the production not closing the popup.
@diadal could you help me?

**Comment by samplecoder122** [comment]
I'm working on Laravel + Vue(Laravel Vue Spa)

**Comment by diadal** [comment]
Did you create the Vue Route?
