### ISSUE TITLE
Linkedin connect not working

### ISSUE THREAD

**Issue by SuperFred** [diadal/vue-social-auth#8]
Linkedin connect not working , response is :
you need to pass the "scope" parameter

Fixed by changing  linkedin parameters like this : 
      requiredUrlParams: ['state','scope'],
      scope: ['r_emailaddress','r_liteprofile'],

instead of 
      requiredUrlParams: ['state'],
      scope: ['r_emailaddress']

**Comment by diadal** [comment]
done
