### ISSUE TITLE
only Google Auth giving error 500

### ISSUE THREAD

**Issue by richardsric** [diadal/vue-social-auth#9]
i have done everything needed to the best of my knowledge. Other Social Medias Facebook and Twitter and Github are all working, except google. it gives me error 500. i can't figure out what could be wrong, i have followed exact same step i used for others.
Is there a reason for this? only the google is giving me error 500 when the script posts to the callback url.

**Comment by diadal** [comment]
check the error log in your backend and make your there is no typo

**Comment by richardsric** [comment]
Actually, i checked the error. it says LEGACY API access not enabled in the account. And i read also that legacy access cannot be enabled and users should use the Google+ API. is there a way to make it work with this library? as any new account cannot have the legacy API enabled, unless it was previously enabled.

**Comment by diadal** [comment]
do it from there `https://console.developers.google.com/apis/dashboard`
<img width="1235" alt="Screenshot 2019-10-23 at 5 46 51 PM" src="https://user-images.githubusercontent.com/19895516/67415564-2c28b480-f5bd-11e9-938b-213339a4cc56.png">

**Comment by richardsric** [comment]
i have. it keepps giving me this error...

    "message": "Client error: `GET https://www.googleapis.com/plus/v1/people/me` resulted in a `403 Forbidden` response:\n{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"Legacy People API has not been used in project ******404337 before or it (truncated...)\n",

I have enabled people's API. it still gives me same error

**Comment by diadal** [comment]
Use the right API data check this https://developers.google.com/people/legacy

**Comment by richardsric** [comment]
Thank you. in the document they are saying i cannot enable legacy on a new project as it's bn shut down. is there a way to make this library work with the suggested api option?

**Comment by diadal** [comment]
just am too busy now I will check and advice it should work

**Comment by richardsric** [comment]
thank you. i will be reminding you. ;)

**Comment by richardsric** [comment]
Hello, is there any update for this? hope i'm not troubling too much. ;)
